version: "3.1"

services:
  mysql_database:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=jardim4565
      - MYSQL_DATABASE=taskmanager
      - MYSQL_ROOT_HOST=%
    ports:
      - "3306:3306"